name: pencatatan_keuangan
description: A new Flutter project.

publish_to: 'none' # Hapus ini jika ingin dipublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  supabase_flutter: ^2.9.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar.png
